### ISSUE TITLE
return value of randombytes() not checked

### ISSUE THREAD

**Issue by dorssel** [microsoft/PQCrypto-LWEKE#29]
For example during key generation:
https://github.com/microsoft/PQCrypto-LWEKE/blob/4210d53c9172dac89a7b288a18b919fa87420300/src/kem.c#L35

`randombytes()` can fail on Windows, which will go unnoticed and will lead to an insecure (possibly completely deterministic) key!

Additionally: the code in `randombytes.c` is not very well written for other reasons. On Linux, the code will simply deadlock if `\dev\urandom` is not available. And if you ever compile without either WINDOWS or NIX, then it defaults to returning `passed` instead of `failed`. But that last point doesn't actually matter, since the return value is not checked anyway...

**Comment by patricklonga** [comment]
Deadlocking on \dev\urandom unavailability is done on purpose (similar to what other open-source libraries do. E.g., see https://github.com/dorssel/xmss-reference/blob/master/randombytes.c). Also, note that the library only compiles for WINDOWS or NIX (otherwise, it throws an error). Therefore, the return values are fine.
I added a couple of checks to verify the return of randombytes in kem.c. Thanks for pointing this out.
